/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SmtpsRouteImport } from './routes/smtps'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVerifySmtpsRouteImport } from './routes/api.public.verify-smtps'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SmtpsRoute = SmtpsRouteImport.update({
  id: '/smtps',
  path: '/smtps',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifySmtpsRoute = ApiPublicVerifySmtpsRouteImport.update({
  id: '/api/public/verify-smtps',
  path: '/api/public/verify-smtps',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/lists': typeof ListsRoute
  '/smtps': typeof SmtpsRoute
  '/sources': typeof SourcesRoute
  '/api/public/verify-smtps': typeof ApiPublicVerifySmtpsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/lists': typeof ListsRoute
  '/smtps': typeof SmtpsRoute
  '/sources': typeof SourcesRoute
  '/api/public/verify-smtps': typeof ApiPublicVerifySmtpsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof CampaignsRoute
  '/lists': typeof ListsRoute
  '/smtps': typeof SmtpsRoute
  '/sources': typeof SourcesRoute
  '/api/public/verify-smtps': typeof ApiPublicVerifySmtpsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/lists'
    | '/smtps'
    | '/sources'
    | '/api/public/verify-smtps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/lists'
    | '/smtps'
    | '/sources'
    | '/api/public/verify-smtps'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/campaigns'
    | '/lists'
    | '/smtps'
    | '/sources'
    | '/api/public/verify-smtps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CampaignsRoute: typeof CampaignsRoute
  ListsRoute: typeof ListsRoute
  SmtpsRoute: typeof SmtpsRoute
  SourcesRoute: typeof SourcesRoute
  ApiPublicVerifySmtpsRoute: typeof ApiPublicVerifySmtpsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smtps': {
      id: '/smtps'
      path: '/smtps'
      fullPath: '/smtps'
      preLoaderRoute: typeof SmtpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-smtps': {
      id: '/api/public/verify-smtps'
      path: '/api/public/verify-smtps'
      fullPath: '/api/public/verify-smtps'
      preLoaderRoute: typeof ApiPublicVerifySmtpsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CampaignsRoute: CampaignsRoute,
  ListsRoute: ListsRoute,
  SmtpsRoute: SmtpsRoute,
  SourcesRoute: SourcesRoute,
  ApiPublicVerifySmtpsRoute: ApiPublicVerifySmtpsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
